../../../../out/host/linux-x86/bin/hidl-gen i_h INfc.hidl INfc.h
../../../../out/host/linux-x86/bin/hidl-gen proxy_cpp INfc.hidl NfcProxy.cpp
../../../../out/host/linux-x86/bin/hidl-gen stubs_cpp INfc.hidl NfcStubs.cpp
../../../../out/host/linux-x86/bin/hidl-gen bp_h INfc.hidl BpNfc.h
../../../../out/host/linux-x86/bin/hidl-gen bn_h INfc.hidl BnNfc.h
../../../../out/host/linux-x86/bin/hidl-gen vts INfc.hidl Nfc.vts
../../../../out/host/linux-x86/bin/hidl-gen i_h INfcClientCallback.hidl INfcClientCallback.h
../../../../out/host/linux-x86/bin/hidl-gen proxy_cpp INfcClientCallback.hidl NfcClientCallbackProxy.cpp
../../../../out/host/linux-x86/bin/hidl-gen stubs_cpp INfcClientCallback.hidl NfcClientCallbackStubs.cpp
../../../../out/host/linux-x86/bin/hidl-gen bp_h INfcClientCallback.hidl BpNfcClientCallback.h
../../../../out/host/linux-x86/bin/hidl-gen bn_h INfcClientCallback.hidl BnNfcClientCallback.h
../../../../out/host/linux-x86/bin/hidl-gen vts INfcClientCallback.hidl NfcClientCallback.vts
