../../../../out/host/linux-x86/bin/hidl-gen i_h INfc.hidl INfc.h
../../../../out/host/linux-x86/bin/hidl-gen all_cpp INfc.hidl NfcAll.cpp
../../../../out/host/linux-x86/bin/hidl-gen bp_h INfc.hidl BpNfc.h
../../../../out/host/linux-x86/bin/hidl-gen bn_h INfc.hidl BnNfc.h
../../../../out/host/linux-x86/bin/hidl-gen vts INfc.hidl Nfc.vts
../../../../out/host/linux-x86/bin/hidl-gen i_h INfcClientCallback.hidl INfcClientCallback.h
../../../../out/host/linux-x86/bin/hidl-gen all_cpp INfcClientCallback.hidl NfcClientCallbackAll.cpp
../../../../out/host/linux-x86/bin/hidl-gen bp_h INfcClientCallback.hidl BpNfcClientCallback.h
../../../../out/host/linux-x86/bin/hidl-gen bn_h INfcClientCallback.hidl BnNfcClientCallback.h
../../../../out/host/linux-x86/bin/hidl-gen vts INfcClientCallback.hidl NfcClientCallback.vts
